# Assignment 1: Linear Algebra and Probability
Andrés Rosso
andresrosso@gmail.com

Let D = {d1, . . . , dn} be a set of documents and T = {t1, . . . , tm} a set of terms (words). Let
T D = (T Di,j )i=1...m,j=1...n be a matrix such that T Di,j corresponds to the number of times
the term ti appears in the document dj . Also, let li be the length, number of characters,
of term ti
, and let L = (l1, . . . , lm) be a column vector. Finally, assume a process where a
document dj is randomly chosen with uniform probability and then a term ti
, present in dj ,
is randomly chosen with a probability proportional to the frequency of ti
in dj.

## Define Objects to Work

In [12]:
import numpy as np

np.seterr(divide='ignore', invalid='ignore')
# Let TD = (T Di,j )i=1...m,j=1...n be a matrix 
# such that T Di,j corresponds to the number of times the term ti appears in the document dj 
TD = np.matrix('2 3 0 3 7; 0 5 5 0 3; 5 0 7 3 3; 3 1 0 9 9; 0 0 7 1 3; 6 9 4 6 0')
print(TD)

[[2 3 0 3 7]
 [0 5 5 0 3]
 [5 0 7 3 3]
 [3 1 0 9 9]
 [0 0 7 1 3]
 [6 9 4 6 0]]


In [13]:
# let li be the length, number of characters, of term ti, and 
# let L = (l1, . . . , lm) be a column vector.
L = np.matrix('5; 2; 3; 6; 4; 3')
print(L)

[[5]
 [2]
 [3]
 [6]
 [4]
 [3]]


## a. Joint Probability of T and D

* Matrix P(T, D) (each position of the matrix, P(T, D)i,j , corresponds to the joint probability
of term ti and document dj , P(ti
, dj ))

The procedure to solve this point is:

* Calculate the probability of get a document d, as d is uniform, the probaility is $$P(D=d)=1/m$$
* Calculate the probability if get a term j in a document d, is proportional to the frecuency so: 
$$ P(T=t_{i,j})=f_{t_{i}}/S_{t}$$
$$ f_{t_{i}}:  frecuency\,  of\,  term \, (i) \, in \, document\,  (j)$$
$$ S_{t}: \, =\,  number \, of \, terms\,  in\,  document\,  (j)\,$$
* Calculate the  matrix that will divide the original matrix to obtain the joing probability matrix
$$ St = TD'I_{mxm}(1/5)$$
* Make the Matrix previously opbtaine a diagonal matrix
$$D=\sum_{i}^{1}IS_{1,t}$$
* Multiply St and TD
$$PTyD = TD*S_{t}$$

In [15]:
     #Counting the number of terms in each document D
     St = TD.transpose()*np.matrix('1; 1; 1; 1; 1; 1')
     #Making the sum of terms a diagonal matrix
     divMtx = np.identity(5)/np.diag(St.A1)
     divMtx[np.isnan(divMtx)] = 0
     print(divMtx)

[[ 0.0625      0.          0.          0.          0.        ]
 [ 0.          0.05555556  0.          0.          0.        ]
 [ 0.          0.          0.04347826  0.          0.        ]
 [ 0.          0.          0.          0.04545455  0.        ]
 [ 0.          0.          0.          0.          0.04      ]]


In [16]:
    #Get the joint probability matrix P(T,D)
    PTyD = TD*divMtx
    PTyD = PTyD*(1/5)
    print(PTyD)

[[ 0.025       0.03333333  0.          0.02727273  0.056     ]
 [ 0.          0.05555556  0.04347826  0.          0.024     ]
 [ 0.0625      0.          0.06086957  0.02727273  0.024     ]
 [ 0.0375      0.01111111  0.          0.08181818  0.072     ]
 [ 0.          0.          0.06086957  0.00909091  0.024     ]
 [ 0.075       0.1         0.03478261  0.05454545  0.        ]]


### Check the solution

$$f(x_{i},y_{j}) > 0$$
$$\sum_{x}^{i} \sum_{y}^{j} f(x_{i},y_{j}) = 1$$

In [17]:
    PTyD.sum()

1.0

## b. Matrix P(T|D)



$$ P(T|D)=\frac{P(TD)}{P(D)} $$


In [18]:
     PD = PTyD.transpose()*np.matrix('1; 1; 1; 1; 1; 1')
     PT = PTyD*np.matrix('1; 1; 1; 1; 1')
     divPD = np.identity(5)/np.diag(PD.A1)
     divPD[np.isnan(divPD)] = 0
     P_T_DADO_D = (PTyD*divPD)
     print(P_T_DADO_D)

[[ 0.125       0.16666667  0.          0.13636364  0.28      ]
 [ 0.          0.27777778  0.2173913   0.          0.12      ]
 [ 0.3125      0.          0.30434783  0.13636364  0.12      ]
 [ 0.1875      0.05555556  0.          0.40909091  0.36      ]
 [ 0.          0.          0.30434783  0.04545455  0.12      ]
 [ 0.375       0.5         0.17391304  0.27272727  0.        ]]


## c. Matrix P(D|T)
$$ P(D|T)=\frac{P(TD)}{P(T)} $$

In [19]:
     divPT = np.identity(6)/np.diag(PT.A1)
     divPT[np.isnan(divPT)] = 0
     P_D_DADO_T = (PTyD.transpose()*divPT).transpose()
     print(P_D_DADO_T)

[[ 0.17654612  0.23539482  0.          0.19259576  0.3954633 ]
 [ 0.          0.45154704  0.35338464  0.          0.19506832]
 [ 0.35787437  0.          0.34853851  0.15616336  0.13742376]
 [ 0.18524987  0.05488885  0.          0.40418153  0.35567975]
 [ 0.          0.          0.64782097  0.09675248  0.25542655]
 [ 0.28373832  0.37831776  0.13158879  0.20635514  0.        ]]


## d. Matrix P(D)

Marginal distribution of D: Is the probabilities of various values of the variables D in the subset without reference to 
the values of the other variable T.

$$ P(D) $$

In [25]:
print(PD)

[[ 0.2]
 [ 0.2]
 [ 0.2]
 [ 0.2]
 [ 0.2]]


## e. Matrix P(T)

Marginal distribution of T: Is the probabilities of various values of the variables T in the subset without reference to 
the values of the other variable D.

$$ P(T) $$

In [27]:
print(PT)

[[ 0.14160606]
 [ 0.12303382]
 [ 0.17464229]
 [ 0.20242929]
 [ 0.09396047]
 [ 0.26432806]]


##f. E(l)

$$E[L]=\sum_{i=1}^{\alpha }x_{_i}p_{_{i}}$$


In [29]:
     diagL = np.identity(6)*np.diag(L.A1)
     diagL[np.isnan(diagL)] = 0
     EL = PT.transpose()*diagL
     print(  EL.sum())

3.86142665788


##g. Var(l)
$$Var(l)=\frac{1}{n}\sum_{i=1}^{n}p_{i}\cdot (x_{i}-\mu )^{2}$$

In [30]:
    varL = np.var(L)
    print(varL)

1.80555555556
